### ISSUE TITLE
Probleme de taille text parametric

### ISSUE THREAD

**Issue by Casella75** [thomasa88/ParametricText#23]
Bonjour,

Depuis la mise à jour de ce matin de Fusion 360 et après discussions avec le Service après vente chez fusion le problème vient de chez vous car il on fait des modification sur la hauteur des textes
Dans l'attente d'une mise a jour de votre part

Cordialement,

**Comment by thomasa88** [comment]
I can reproduce it in Fusion 360 v. 2.0.10244.

Duplicate of #21

**Comment by thomasa88** [comment]
Duplicate of #21

**Comment by Casella75** [comment]
La dernière version
V2.0.10244


-------------
Frédéric Berlocher

10 Quai des Belges 
67000 STRASBOURG
Tel : 06 35 27 01 15

**Comment by Casella75** [comment]
La police revient toujours à 10mm
L’équipe de Autodesk a fait le test ils on le même problème que moi


-------------
Frédéric Berlocher

10 Quai des Belges 
67000 STRASBOURG
Tel : 06 35 27 01 15

**Comment by thomasa88** [comment]
Thank you for reporting back that they can reproduce it. Please consider using issue #21 for further info on this problem, as this is a duplicate of that issue.
I have created a bug report on the Autodesk forum. It is a problem in their interface for writing add-ins. Unfortunately, it might take some time before we get a fix..
https://forums.autodesk.com/t5/fusion-360-api-and-scripts/bug-setting-sketchtext-properties-resets-text-height-since-v-2-0/td-p/10356396
