### ISSUE TITLE
Does not update when parameters get changed from other scripts

### ISSUE THREAD

**Issue by valadas** [thomasa88/ParametricText#27]
**Describe the bug**
I am not sure if this is a bug or feature request or just a cry for help. I am new to python and fairly new to fusion 360 also. I am writing a small script that will batch process a model to export an .stl file for multiple sizes automatically. The script appears to be working but the text does not update. Is there some sort of fusion 360 event I need to fire for ParametricText to run when that parameter changes ?

Here is my current script:

```python
import adsk.core, adsk.fusion, adsk.cam, traceback

def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)

        components = design.rootComponent
        folder = 'D:/Users/Daniel Valadas/Downloads/kit/'
        sizeParam = design.allParameters.itemByName('size')
        sizes = [19.0, 19.2, 19.4, 19.6]

        for size in sizes:
            sizeParam.expression = str(size)
            filename = folder + str(size) + '.stl'
            adsk.doEvents()

            # Save file
            exportMgr = adsk.fusion.ExportManager.cast(design.exportManager)
            stlOptions = exportMgr.createSTLExportOptions(comp)
            stlOptions.meshRefinement = adsk.fusion.MeshRefinementSettings.MeshRefinementMedium
            stlOptions.filename = filename
            stlOptions.isOneFilePerBody = True
            exportMgr.execute(stlOptions)

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
```

**To Reproduce**
1. Create some cylinder with the size parameter used on a text sketch, one body is the cylinder with this size and the other body is an extrusion of the text.
2. Run the above script (maybe change the hardcoded folder path for your scenario)
3. Open up the generated stl files
4. Notice the cylinders got updated but not the text

**Expected behavior**
Well, not sure if anything is wrong or I just need to fire up some event to simulate that a user changed the parameter and closed the window

**Software**
 - OS: Windows
 - Fusion 360 version: [Help->About]
 - ParametricText version: v 2.0.10356

Do not forget to "Subscribe" to the issue if you want updates!

**Comment by valadas** [comment]
Ha, I managed to fiddle my way through and actually modify the actual text in the script I built instead of relying on this plugin to detect the parameter change. Sooo, feel free to close if this is not of interest, if not I am happy to help test out possibilities.

And just FYI if someone needs to do about the same (lots of hardcoded stuff here though as it is just for this specific design), but here is how I did it:

```python
textSketch = design.allComponents.itemByName("plug").sketches.itemByName("text")
            for text in textSketch.sketchTexts:
                text.text = str(size)
```

**Comment by thomasa88** [comment]
Hi,

Nice that you managed to solve the immediate problem.

I can think of two ways of doing this:

- I have had plans of supporting update of texts when running Compute all, if I can trigger the update just before Compute all runs (it's somewhat complicated due to the add-in itself eubnikg compute all, but a flag variable can likely be used). Then your script could call Compute All. 

- Add support for a custom event (Application.registerCustomEvent) that can be triggered.

Thinking about it, the first option is more general, as it might help regular users that get problems with e.g. a text not updating after renaming a component. However, it is more prone to bugs and will need more testing. So until it is needed, I'd rather not run anything on compute all until users are seeing issues.

That leaves the second option.

I'll see if I can come back with something in a few days.

(I just remembered that listening to parameter expressions is done by watching for the parameter dialog Command to finish, so a workaround is also to open that dialog and close it.. Might be possible with Text Commands..)

**Comment by valadas** [comment]
Awesome, well in my case it is solved, soooo leaving the issue here if it's a use case of interest, but won't cry if the issue get's closed :) And thanks for this awesome plugin, super useful!

**Comment by thomasa88** [comment]
Ended up having less hand on time than I thought. Dropping it for now.

**Comment by valadas** [comment]
Cool cool, don't you wish there were 48 hours in each day!
