### ISSUE TITLE
Changing parameter resets flip, angle

### ISSUE THREAD

**Issue by evilC** [thomasa88/ParametricText#5]
I am looking at leveraging this plugin to make a temperature tower tool
eg like I did here: https://www.thingiverse.com/thing:2493504/comments#comment-3415950

The idea being that I create a Fusion design using User Parameters to store the temperature for each section, plus an AHK script which will adjust the temperatures in the Fusion User Parameters dialog, then tab into Cura and set up the temp for each layer

However, when I edit the value of a User Parameter, the angle and flip settings of the Text object in Fusion get changed
ie here, when I change the temp of layer 1 in the User Parameters dialog from 240 to 241, the text flips upside-down
![xOcYZFNGrV](https://user-images.githubusercontent.com/1719428/96036759-d481f980-0e5c-11eb-8197-bd0d7d824484.gif)

Fusion Project: https://a360.co/3o1l4GK

**Comment by thomasa88** [comment]
Hi, This is a known issue: https://github.com/thomasa88/ParametricText#known-limitations

The workaround I have found, if using a plane, is to place the text on a body instead of a plane. I have not hit the problem when placing texts on bodies. It might also be possible to use an angled plane (not on my computer, but the name should be something like that) rotated 180 degrees, to get a plane that is flipped.

**Comment by evilC** [comment]
What a ball-ache. Thanks though, seems to work. Apologies for not RTFM

**Comment by thomasa88** [comment]
Fusion 360 version 2.0.9142 seems to have fixed this.
