### ISSUE TITLE
Add on won't run

### ISSUE THREAD

**Issue by Yowie22** [thomasa88/ParametricText#8]
Hi, Not sure what I am doing wrong, could you help please. I have installed the Add on as per instructions. It shows in the addon drop down menu, but Icant get it to run. 
![image](https://user-images.githubusercontent.com/36324188/98434066-6f9a8600-2120-11eb-83d4-0ec053dc4b6e.png)

**Comment by thomasa88** [comment]
Hi, not getting any error messages usually means that the add-in code barely manages to start.

One thing that can lead to this is that the thomasa88lib directory is empty, which usually happens if one downloads the zip file created by github or clones the oeject without submodules.

Can you confirm that you downloaded the zip file from the release page?

If so, what version of the add-in are you using and which version of fusion? (It's under ? -> About or similar).

**Comment by Yowie22** [comment]
I downloaded the zip file and you are right the thomasa88lib directory is empty.
I did it via Github this time and all is fine now.
Thanks for the prompt reply and your effort on the addon.

**Comment by thomasa88** [comment]
Thanks for confirming. I have added some code, for the next release, that will detect if thomasa88lib is missing.
